module.exports = {
    buildStatusInterval: 1000 * 60,
    refreshInterval: 1000 * 60,
    versionUpdateInterval: 1000 * 60,
    //refreshInterval: 1000 * 10,
    dateFormat: 'YYYY-MM-DD HH:mm:SS',
    dateShortFormat: 'MM/DD HH:mm',
    layout: 'list',
    defaultBranch: 'master',
    selectableBranches: ['develop', 'master'],
    apiEndpoint: process.env.API_ENDPOINT,
    chartColors: ["#607D8B", "#66bb6a"],
    reportCategories: [
        'performance',
        'pwa',
        'accessibility',
        'best-practices',
        'seo',
        'dreipol',
        'psi',
    ],
    whitepageAlerts: 0.8,
    diffAlerts: 0.2,
};
