import { REPORT_AUDIT_KEYS } from '../../../config/audit';

export const EXPORTED_TIMINGS = [
    REPORT_AUDIT_KEYS.PERFORMANCE,
    REPORT_AUDIT_KEYS.SEO,
    //REPORT_AUDIT_KEYS.ACCESSIBILITY,
    //REPORT_AUDIT_KEYS.BEST_PRACTICES,
];
